from _typeshed import Incomplete
from galaxy.api.jsonrpc import ApplicationError, UnknownError

class AuthenticationRequired(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class BackendNotAvailable(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class BackendTimeout(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class BackendError(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class TooManyRequests(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class UnknownBackendResponse(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class InvalidCredentials(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class NetworkError(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class ProtocolError(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class TemporaryBlocked(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class Banned(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class AccessDenied(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class FailedParsingManifest(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class TooManyMessagesSent(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class IncoherentLastMessage(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class MessageNotFound(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...

class ImportInProgress(ApplicationError):
    def __init__(self, message: str = ..., data: Incomplete | None = ...) -> None: ...
