from unittest.mock import MagicMock

class AsyncMock(MagicMock):
    async def __call__(self, *args, **kwargs): ...

def coroutine_mock(): ...
async def skip_loop(iterations: int = ...) -> None: ...
async def async_return_value(return_value, loop_iterations_delay: int = ...): ...
async def async_raise(error, loop_iterations_delay: int = ...) -> None: ...
